appinfo/info.xml
required for happy CI on #9.
cc @MorrisJobke
=> fix server dependency version

lib/AppInfo/Application.php, lib/Service/SmsProvider/PlaySMS.php
playSMS is a free and open source SMS management software.
A flexible Web-based mobile portal system that it can be made to fit to various services such as an SMS gateway, bulk SMS provider, personal messaging system, corporate and group communication tools.
It comes with a Webservices API which can be used to automate SMS sending.
See: https://playsms.org/about/
=> Add PlaySMS gateway provider

README.md
As suggested [here](https://github.com/nextcloud/twofactor_totp/pull/144#issuecomment-282540219)
=> Add Login with external apps to README.md

lib/Provider/SmsProvider.php
@emresaracoglu please review and test :-)
Fixes #13
=> Add missing config key when querying the phone number

.travis.yml
Apparently the Travis image contains a newer version which seems to be incompatible with nc and this app.
=> Downgrade to phpunit5.7

README.md, lib/AppInfo/Application.php, lib/Service/SmsProvider/Telegram.php
This was developed by @Dretech. Since I could not push to #27, I've created this PR to fix the coding style and make use of the HTTP client for the Telegram API call.
@Dretech please test again. I do not use/have Telegram so I cannot.
=> Telegram integration

lib/AppInfo/Application.php, lib/Exception/SmsTransmissionException.php, lib/Provider/SmsProvider.php, lib/Service/ISmsService.php, lib/Service/SmsProvider/PlaySMS.php, lib/Service/SmsProvider/SignalGateway.php, lib/Service/SmsProvider/Telegram.php, lib/Service/SmsProvider/WebSmsDe.php
@rullzer, this one is for you :heart_eyes_cat:
=> Make app strict

.gitignore, composer.json, composer.lock, lib/Provider/SmsProvider.php, lib/Service/SmsProvider/SignalGateway.php, tests/Unit/Provider/SmsProviderTest.php
It's the very same OTP class used in the TOTP app, so this caused conflicts.
=> Use session-bound password instead of OTP

README.md, doc/admin/README.md
=> Document Signal gateway configuration

composer.lock, lib/Controller/SettingsController.php, lib/Provider/SmsProvider.php, lib/Provider/State.php, lib/Service/IGateway.php, lib/Service/SetupService.php, lib/Service/StateStorage.php, tests/Unit/Provider/SmsProviderTest.php, tests/Unit/Provider/StateTest.php, tests/Unit/Service/SetupServiceTest.php, tests/Unit/Service/StateStorageTest.php
Ref https://github.com/ChristophWurst/twofactor_gateway/projects/1#card-11846348
=> Make provider stateful

js/webpack.base.config.js, package.json
=> Fix js build

CHANGELOG.md, appinfo/info.xml, package-lock.json, package.json
=> Release 0.7.0

lib/AppInfo/Application.php, lib/Provider/SmsProvider.php, lib/Provider/State.php, lib/Service/Gateway/IGateway.php, lib/Service/Gateway/SMS/PlaySMSGateway.php, lib/Service/Gateway/SMS/WebSmsGateway.php, lib/Service/Gateway/Signal/Gateway.php, lib/Service/Gateway/Telegram/Gateway.php, lib/Service/Gateway/TestGateway.php, lib/Service/SetupService.php, lib/Service/StateStorage.php, tests/Unit/Provider/SmsProviderTest.php, tests/Unit/Service/SetupServiceTest.php, tests/Unit/Service/StateStorageTest.php
=> Refactor gateway namespaces in preparation for #90

js/components/GatewaySettings.vue, js/service/registration.js, lib/Controller/SettingsController.php, lib/Provider/State.php
Ref https://github.com/nextcloud/twofactor_gateway/projects/2#card-12406923.
=> Show gateway not configured info in user settings

CHANGELOG.md, appinfo/info.xml, package-lock.json, package.json
=> Release 0.8.0

doc/admin/README.md
@morph027 would you be interested in helping develop this app? I could use some help in reviewing and testing changes, so would be awesome if you don't mind me assigning you as reviewer :smile:
=> Document Telegram gateway setup

js/components/GatewaySettings.vue, js/components/SignalInstructions.vue, js/components/TelegramInstructions.vue, js/views/Settings.vue
This needs l10n in the future and also the wording can probably be improved, but it's a start.
Fixes #82.
=> Add basic setup instructions for the user settings

lib/Command/Configure.php, lib/Service/Gateway/SMS/Provider/ClockworkSMS.php, lib/Service/Gateway/SMS/Provider/ClockworkSMSConfig.php, lib/Service/Gateway/SMS/Provider/ProviderFactory.php
Added https://www.clockworksms.com/ as provider.
=> added clockworksms as provider

js/components/GatewaySettings.vue
=> Fix loading animation after state has been loaded

CHANGELOG.md, appinfo/info.xml, package-lock.json, package.json
=> Release 0.10.0

CHANGELOG.md, appinfo/info.xml, package-lock.json, package.json
=> Release v0.10.1

doc/Admin Documentation.md, lib/Command/Configure.php, lib/Service/Gateway/SMS/Provider/ProviderFactory.php, lib/Service/Gateway/SMS/Provider/PuzzelSMS.php, lib/Service/Gateway/SMS/Provider/PuzzelSMSConfig.php
Hi, I've added support using Puzzel as 2FA via SMS. 
Please review and let me know if there is anything that must be changed.
=> Added support using Puzzel as 2FA via SMS. 

CHANGELOG.md, appinfo/info.xml, package-lock.json, package.json
=> Release v0.11.0

doc/Admin Documentation.md, lib/Command/Configure.php, lib/Service/Gateway/SMS/Provider/EcallSMS.php, lib/Service/Gateway/SMS/Provider/EcallSMSConfig.php, lib/Service/Gateway/SMS/Provider/ProviderFactory.php
Supersedes https://github.com/nextcloud/twofactor_gateway/pull/182.
=> Add eCall SMS provider

CHANGELOG.md, appinfo/info.xml, package-lock.json, package.json
cc @fblackburn1 @FabianZihlmann @j-ed @morph027 please test :)
Beta1
=> Release v0.12.0

CHANGELOG.md, appinfo/info.xml, package-lock.json, package.json
cc @MaKess  @fblackburn1 @FabianZihlmann @j-ed @morph027 for testing :)
=> Release v0.13.0

.travis.yml, appinfo/info.xml
@fblackburn1 @j-ed @kimsyversen @Dretech please review
=> Add Nextcloud 16 support, drop 15

CHANGELOG.md, appinfo/info.xml, package-lock.json, package.json
@FabianZihlmann @j-ed @morph027 @fblackburn1 @MaKess @mmartinortiz @binford6000 @parreitu @Dretech @DieserMerlin @Freekers @djpremier  please review & test :)
=> Release v0.14.0

README.md
Also slightly reword the link to the device management documentation page.
=> Fix the reference links in the readme.

doc/Admin Documentation.md, lib/Command/Configure.php, lib/Service/Gateway/SMS/Provider/ProviderFactory.php, lib/Service/Gateway/SMS/Provider/SpryngSMS.php, lib/Service/Gateway/SMS/Provider/SpryngSMSConfig.php
Squashed and cleaned-up version of https://github.com/nextcloud/twofactor_gateway/pull/236
=> Add Spryng as SMS provider

doc/Admin Documentation.md, lib/Command/Configure.php, lib/Service/Gateway/SMS/Provider/ProviderFactory.php, lib/Service/Gateway/SMS/Provider/Sms77Io.php, lib/Service/Gateway/SMS/Provider/Sms77IoConfig.php
Rebased and cleaned up version of https://github.com/nextcloud/twofactor_gateway/pull/294
=> Add sms77io SMS provider

lib/Command/Configure.php
as requested per #302
twofactor_gateway/lib/Service/Gateway/SMS/Provider/Sms77Io.php already was correct
changes worked for me to set up sms77.io HTTP API key
(sorry, took two false PRs until I get signoff right)
=> Add sms77 to help and fix case selection string

.travis.yml, appinfo/info.xml
Signed-off-by: Jordan Bieder <jordan.bieder@uliege.be>
=> Update max version

lib/Service/Gateway/SMS/Provider/Sms77Io.php
Signed-off-by: André Matthies <matthiez@gmail.com>
=> sms77io: added sender identifer for improved statistics on our side

doc/Admin Documentation.md, lib/Command/Configure.php, lib/Service/Gateway/SMS/Provider/ClickSend.php, lib/Service/Gateway/SMS/Provider/ClickSendConfig.php, lib/Service/Gateway/SMS/Provider/ProviderFactory.php
Adds clicksend.com as SMS Provider.
I hope it is okay to PR-without-Issue...
Signed-off-by: Henning Bopp <henning.bopp@gmail.com>
=> Add ClickSend.com SMS Gateway

.travis.yml, appinfo/info.xml, composer.json, composer.lock
@henry-nicolas @fblackburn1 @j-ed @piti-diablotin please review :)
Ref https://github.com/nextcloud/twofactor_totp/pull/922 https://github.com/nextcloud/twofactor_u2f/pull/734
=> Allow Nextcloud 20, drop Nextcloud 17

doc/Admin Documentation.md, lib/Command/Configure.php, lib/Service/Gateway/SMS/Provider/ProviderFactory.php, lib/Service/Gateway/SMS/Provider/Voipbuster.php, lib/Service/Gateway/SMS/Provider/VoipbusterConfig.php
Like #378, but squashed.
cc @JdeJongATS :)
=> Added Voipbuster SMS provider

lib/Command/Configure.php, lib/Command/Status.php, lib/Command/Test.php
Fix default return to work with new version of Symfony console.
=> Return success on command

CHANGELOG.md, appinfo/info.xml, composer.json, package.json
This is just a versions bump, no code is changed or verified that all code works with PHP 8.1.
=> Allow for NC24 and PHP8.1, remove PHP 7.2

.github/workflows/phpunit.yml, appinfo/info.xml
Signed-off-by: Vitor Mattos <vitor@php.rio>
=> Bump server version

.github/workflows/appstore-build-publish.yml, .github/workflows/package.yml
Signed-off-by: Vitor Mattos <vitor@php.rio>
=> Remove webpack from workflow

doc/Admin Documentation.md, lib/Command/Configure.php, lib/Service/Gateway/SMS/Provider/ClickatellPortal.php, lib/Service/Gateway/SMS/Provider/ClickatellPortalConfig.php, lib/Service/Gateway/SMS/Provider/ProviderFactory.php
=> Clickatell.com API (SMS Platform)
